application: bseu-fm
version: 4
runtime: python27
threadsafe: yes
api_version: 1


handlers:

- url: /static
  static_dir: static

- url: /img
  script: dispatch.img_app

- url: .*
  script: dispatch.feed_app


libraries:
 - name: django
   version: 1.2

builtins:
- appstats: on
- remote_api: on

env_variables:
  DJANGO_SETTINGS_MODULE: 'settings'